apiVersion: v1
kind: Service
metadata:
  name: health-service
spec:
  selector:
    app: web
  ports:
    - name: web
      port: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: health-service-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: health-service
          image: 776968139487.dkr.ecr.us-east-1.amazonaws.com/health-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080