package com.health.healthlakeservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.util.*;


@DynamoDBTable(tableName="healthcareprojects")
@Data
@Builder
@AllArgsConstructor
/**
 * Class representing Healthcare Service
 */
public class HealthcareProject {

    private String id;
    private String name;
    private String description;
    private String manager;
    private Date startDate;
    private Date endDate;
    private List<FhirResourceFlyweight> fhirResources;


    public HealthcareProject() {
        fhirResources = new ArrayList<>();
    }

    @DynamoDBHashKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName="name")
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName="description")
    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute(attributeName="manager")
    public String getManager() {
        return manager;
    }
    public void setManager(String manager) {
        this.manager = manager;
    }

    @DynamoDBAttribute(attributeName="startDate")
    public Date getStartDate() {
        return startDate;
    }
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @DynamoDBAttribute(attributeName="endDate")
    public Date getEndDate() {
        return endDate;
    }
    public void setEndDate (Date endDate) {
        this.endDate = endDate;
    }

    @DynamoDBAttribute(attributeName="fhirResources")
    public List<FhirResourceFlyweight> getFhirResources() {
        return fhirResources;
    }
    public void setFhirResources(List<FhirResourceFlyweight> fhirResources) {
        this.fhirResources = fhirResources;
    }


    public boolean addResource(FhirResourceFlyweight resourceInfo) {
        if (resourceInfo == null) {
            return false;
        }

        if (fhirResources.contains(resourceInfo)) {
            return false;
        }

        return fhirResources.add(resourceInfo);
    }

    public boolean removeResource(FhirResourceFlyweight resourceInfo) {
        if (resourceInfo == null) {
            return false;
        }

        if (! fhirResources.contains(resourceInfo)) {
            return false;
        }

        return fhirResources.remove(resourceInfo);
    }

    @Override
    public String toString() {
        return "HealthcareProject{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", manager='" + manager + '\'' +
                ", startDate=" + startDate +
                ", endDate=" + endDate +
                ", fhirResources=" + fhirResources +
                '}';
    }
}
